name: Deploy 2048 to ECS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # 👈 Needed for OIDC
      contents: read

    env:
      VAULT_ADDR: http://34.42.214.187:8200   # or https://vault.example.com if TLS enabled
      AWS_REGION: us-west-2
      ECR_REPO_URL: 293088445135.dkr.ecr.us-west-2.amazonaws.com/vault-cicd-2048
      ECS_CLUSTER: vault-cicd-2048-dev-cluster
      ECS_SERVICE: vault-cicd-2048-dev-svc

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Vault CLI
        run: |
          curl -fsSL https://releases.hashicorp.com/vault/1.17.5/vault_1.17.5_linux_amd64.zip -o vault.zip
          unzip vault.zip
          sudo mv vault /usr/local/bin/
          vault --version

      - name: Get GitHub OIDC token
        id: jwt
        run: |
          echo "token=$(curl -sSL \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://vault" \
            | jq -r '.value')" >> $GITHUB_ENV
      
      - name: Login to Vault with GitHub OIDC
        run: |
          vault write -format=json auth/jwt/login \
            role="github-ecs-deployer" \
            jwt="${{ env.token }}" \
            > vault-response.json

          cat vault-response.json
          echo "VAULT_TOKEN=$(jq -r .auth.client_token vault-response.json)" >> $GITHUB_ENV
          
      - name: Get AWS creds from Vault
        run: |
          set -euo pipefail
          export VAULT_TOKEN=${{ env.VAULT_TOKEN }}
          CREDS=$(vault read -format=json aws/creds/ecs-deploy-role)
          echo "AWS_ACCESS_KEY_ID=$(echo $CREDS | jq -r .data.access_key)" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$(echo $CREDS | jq -r .data.secret_key)" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=$(echo $CREDS | jq -r .data.security_token)" >> $GITHUB_ENV

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Configure AWS CLI Region
        run: aws configure set region $AWS_REGION

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO_URL

      - name: Build, Tag, and Push Docker Image
        run: |
          IMAGE_TAG=latest
          docker build -t $ECR_REPO_URL:$IMAGE_TAG .
          docker push $ECR_REPO_URL:$IMAGE_TAG
          echo "IMAGE=$ECR_REPO_URL:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Update ECS Service
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE \
            --force-new-deployment
